# Generated by Django 5.1.7 on 2025-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
