# Generated by Django 5.1.7 on 2025-03-30 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrole',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='honorary',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minimumfee',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minimumfee',
            name='name',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='radar',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radar',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='samplefee',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1555cbc8-f90a-4265-a82f-581205b5c891'), primary_key=True, serialize=False),
        ),
    ]
