# Generated by Django 5.1.7 on 2025-03-30 22:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalflow', '0002_alter_businessrole_guid_alter_dispatcher_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrole',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='honorary',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minimumfee',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radar',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samplefee',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samplefee',
            name='name',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('3144ae34-b861-4754-b61e-359227d5aada'), primary_key=True, serialize=False),
        ),
    ]
