# Generated by Django 5.1.7 on 2025-03-31 00:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalflow', '0003_alter_businessrole_guid_alter_dispatcher_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrole',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='honorary',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minimumfee',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radar',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samplefee',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('guid', models.UUIDField(default=uuid.UUID('7c044906-9e9e-42a7-838f-73073b1a7070'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_name', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=250)),
                ('business_contact', models.CharField(max_length=250)),
                ('business_role', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('mobile_phone', models.CharField(max_length=250)),
                ('simulation_cost_email', models.CharField(max_length=250)),
                ('business_email', models.CharField(max_length=250)),
                ('honorary_value', models.CharField(max_length=250)),
                ('sdas', models.CharField(max_length=250)),
                ('validity_attorney', models.CharField(max_length=250)),
                ('exchange_closing', models.CharField(max_length=250)),
                ('exchange_where', models.CharField(max_length=250)),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.dispatcher')),
                ('honorary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.honorary')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.insurance')),
                ('minimum_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.minimumfee')),
                ('radar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.radar')),
                ('sample_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.samplefee')),
                ('tax_regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globalflow.taxregime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
